name: Deploy to EC2

on:
  push:
    branches:
      - development  # Trigger deployment on push to the development branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Use your PEM key from GitHub Secrets

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Set your desired Node.js version

      - name: Install dependencies
        run: |
          npm install  # Install dependencies

      - name: Build the React app 
        run: |
          npm run build  # Build the React app

      - name: Upload files to EC2
        run: |
          # Specify the path of your files to upload (upload build folder)
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./dist/* ubuntu@13.51.171.2:/home/ubuntu/onstep/react/
