name: Deploy to EC2

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Upload files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./dist/* ubuntu@13.51.171.2:/home/ubuntu/tmp/

      - name: Move uploaded files into final folder
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.171.2 << 'EOF'
            sudo rm -rf /home/ubuntu/onstep/react/*
            sudo mv /home/ubuntu/tmp/* /home/ubuntu/onstep/react/
          EOF
